const repos = [
  {
    name: "design-system",
    visibility: "Public",
    language: "React",
    size: 7320,
    lastUpdated: 1,
  },
  {
    name: "codeant-ci-app",
    visibility: "Private",
    language: "Javascript",
    size: 5871,
    lastUpdated: 2,
  },
  {
    name: "analytics-dashboard",
    visibility: "Private",
    language: "Python",
    size: 4521,
    lastUpdated: 5,
  },
  {
    name: "mobile-app",
    visibility: "Public",
    language: "Swift",
    size: 3096,
    lastUpdated: 3,
  },
  {
    name: "e-commerce-platform",
    visibility: "Private",
    language: "Java",
    size: 6210,
    lastUpdated: 6,
  },
  {
    name: "blog-website",
    visibility: "Public",
    language: "HTML/CSS",
    size: 1876,
    lastUpdated: 4,
  },
  {
    name: "social-network",
    visibility: "Private",
    language: "PHP",
    size: 5432,
    lastUpdated: 7,
  },
  {
    name: "photo-editor",
    visibility: "Public",
    language: "C++",
    size: 2500,
    lastUpdated: 8,
  },
  {
    name: "todo-list-app",
    visibility: "Private",
    language: "JavaScript",
    size: 1200,
    lastUpdated: 9,
  },
  {
    name: "chat-application",
    visibility: "Public",
    language: "React",
    size: 3000,
    lastUpdated: 10,
  },
  {
    name: "weather-app",
    visibility: "Public",
    language: "Python",
    size: 1000,
    lastUpdated: 11,
  },
  {
    name: "expense-tracker",
    visibility: "Private",
    language: "TypeScript",
    size: 1800,
    lastUpdated: 12,
  },
  {
    name: "portfolio-site",
    visibility: "Public",
    language: "HTML/CSS",
    size: 600,
    lastUpdated: 13,
  },
  {
    name: "game-app",
    visibility: "Private",
    language: "C++",
    size: 3200,
    lastUpdated: 14,
  },
  {
    name: "api-server",
    visibility: "Private",
    language: "Node.js",
    size: 2300,
    lastUpdated: 15,
  },
  {
    name: "project-manager",
    visibility: "Public",
    language: "Java",
    size: 4000,
    lastUpdated: 16,
  },
  {
    name: "notes-app",
    visibility: "Private",
    language: "JavaScript",
    size: 1500,
    lastUpdated: 17,
  },
  {
    name: "image-compressor",
    visibility: "Public",
    language: "Python",
    size: 1800,
    lastUpdated: 18,
  },
  {
    name: "blog-editor",
    visibility: "Private",
    language: "TypeScript",
    size: 1900,
    lastUpdated: 19,
  },
  {
    name: "data-visualizer",
    visibility: "Public",
    language: "JavaScript",
    size: 2500,
    lastUpdated: 20,
  },
  {
    name: "learning-platform",
    visibility: "Private",
    language: "Java",
    size: 4200,
    lastUpdated: 21,
  },
  {
    name: "stock-tracker",
    visibility: "Public",
    language: "Python",
    size: 2000,
    lastUpdated: 22,
  },
  {
    name: "news-aggregator",
    visibility: "Private",
    language: "React",
    size: 3000,
    lastUpdated: 23,
  },
  {
    name: "quiz-app",
    visibility: "Public",
    language: "JavaScript",
    size: 1300,
    lastUpdated: 24,
  },
  {
    name: "fitness-tracker",
    visibility: "Private",
    language: "Java",
    size: 3100,
    lastUpdated: 25,
  },
  {
    name: "recipe-app",
    visibility: "Public",
    language: "Swift",
    size: 2700,
    lastUpdated: 26,
  },
  {
    name: "e-learning-platform",
    visibility: "Private",
    language: "Python",
    size: 3500,
    lastUpdated: 27,
  },
  {
    name: "music-player",
    visibility: "Public",
    language: "TypeScript",
    size: 2900,
    lastUpdated: 28,
  },
  {
    name: "video-streaming-app",
    visibility: "Private",
    language: "React",
    size: 4000,
    lastUpdated: 29,
  },
  {
    name: "calendar-app",
    visibility: "Public",
    language: "JavaScript",
    size: 1800,
    lastUpdated: 30,
  },
  {
    name: "library-system",
    visibility: "Private",
    language: "C++",
    size: 3100,
    lastUpdated: 31,
  },
  {
    name: "chatbot",
    visibility: "Public",
    language: "Python",
    size: 2200,
    lastUpdated: 32,
  },
  {
    name: "survey-app",
    visibility: "Private",
    language: "Node.js",
    size: 2300,
    lastUpdated: 33,
  },
];

export default repos;
